/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as DashboardMapsLayoutRouteImport } from './routes/_dashboard/maps/layout'
import { Route as DashboardMapLayoutRouteImport } from './routes/_dashboard/map/layout'
import { Route as DashboardSyncIndexRouteImport } from './routes/_dashboard/sync/index'
import { Route as DashboardMapsIndexRouteImport } from './routes/_dashboard/maps/index'
import { Route as DashboardMapIndexRouteImport } from './routes/_dashboard/map/index'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardAdminRouteRouteImport } from './routes/_dashboard/admin/route'
import { Route as DashboardMapsMapIdIndexRouteImport } from './routes/_dashboard/maps/$mapId/index'
import { Route as DashboardAdminEventsIndexRouteImport } from './routes/_dashboard/admin/events/index'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardMapsLayoutRoute = DashboardMapsLayoutRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardMapLayoutRoute = DashboardMapLayoutRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardSyncIndexRoute = DashboardSyncIndexRouteImport.update({
  id: '/sync/',
  path: '/sync/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardMapsIndexRoute = DashboardMapsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMapsLayoutRoute,
} as any)
const DashboardMapIndexRoute = DashboardMapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMapLayoutRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/admin/route',
  path: '/admin/route',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardMapsMapIdIndexRoute = DashboardMapsMapIdIndexRouteImport.update({
  id: '/$mapId/',
  path: '/$mapId/',
  getParentRoute: () => DashboardMapsLayoutRoute,
} as any)
const DashboardAdminEventsIndexRoute =
  DashboardAdminEventsIndexRouteImport.update({
    id: '/admin/events/',
    path: '/admin/events/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/map': typeof DashboardMapLayoutRouteWithChildren
  '/maps': typeof DashboardMapsLayoutRouteWithChildren
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/route': typeof DashboardAdminRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/map/': typeof DashboardMapIndexRoute
  '/maps/': typeof DashboardMapsIndexRoute
  '/sync/': typeof DashboardSyncIndexRoute
  '/admin/events/': typeof DashboardAdminEventsIndexRoute
  '/maps/$mapId/': typeof DashboardMapsMapIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth': typeof AuthIndexRoute
  '/admin/route': typeof DashboardAdminRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/map': typeof DashboardMapIndexRoute
  '/maps': typeof DashboardMapsIndexRoute
  '/sync': typeof DashboardSyncIndexRoute
  '/admin/events': typeof DashboardAdminEventsIndexRoute
  '/maps/$mapId': typeof DashboardMapsMapIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/_dashboard/map': typeof DashboardMapLayoutRouteWithChildren
  '/_dashboard/maps': typeof DashboardMapsLayoutRouteWithChildren
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/_dashboard/admin/route': typeof DashboardAdminRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/map/': typeof DashboardMapIndexRoute
  '/_dashboard/maps/': typeof DashboardMapsIndexRoute
  '/_dashboard/sync/': typeof DashboardSyncIndexRoute
  '/_dashboard/admin/events/': typeof DashboardAdminEventsIndexRoute
  '/_dashboard/maps/$mapId/': typeof DashboardMapsMapIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/map'
    | '/maps'
    | '/auth/signup'
    | '/auth/'
    | '/admin/route'
    | '/api/auth/$'
    | '/dashboard/'
    | '/map/'
    | '/maps/'
    | '/sync/'
    | '/admin/events/'
    | '/maps/$mapId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/signup'
    | '/auth'
    | '/admin/route'
    | '/api/auth/$'
    | '/dashboard'
    | '/map'
    | '/maps'
    | '/sync'
    | '/admin/events'
    | '/maps/$mapId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/auth'
    | '/_dashboard/map'
    | '/_dashboard/maps'
    | '/auth/signup'
    | '/auth/'
    | '/_dashboard/admin/route'
    | '/api/auth/$'
    | '/_dashboard/dashboard/'
    | '/_dashboard/map/'
    | '/_dashboard/maps/'
    | '/_dashboard/sync/'
    | '/_dashboard/admin/events/'
    | '/_dashboard/maps/$mapId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_dashboard/maps': {
      id: '/_dashboard/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof DashboardMapsLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/map': {
      id: '/_dashboard/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof DashboardMapLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/sync/': {
      id: '/_dashboard/sync/'
      path: '/sync'
      fullPath: '/sync/'
      preLoaderRoute: typeof DashboardSyncIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/maps/': {
      id: '/_dashboard/maps/'
      path: '/'
      fullPath: '/maps/'
      preLoaderRoute: typeof DashboardMapsIndexRouteImport
      parentRoute: typeof DashboardMapsLayoutRoute
    }
    '/_dashboard/map/': {
      id: '/_dashboard/map/'
      path: '/'
      fullPath: '/map/'
      preLoaderRoute: typeof DashboardMapIndexRouteImport
      parentRoute: typeof DashboardMapLayoutRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/admin/route': {
      id: '/_dashboard/admin/route'
      path: '/admin/route'
      fullPath: '/admin/route'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/maps/$mapId/': {
      id: '/_dashboard/maps/$mapId/'
      path: '/$mapId'
      fullPath: '/maps/$mapId/'
      preLoaderRoute: typeof DashboardMapsMapIdIndexRouteImport
      parentRoute: typeof DashboardMapsLayoutRoute
    }
    '/_dashboard/admin/events/': {
      id: '/_dashboard/admin/events/'
      path: '/admin/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof DashboardAdminEventsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardMapLayoutRouteChildren {
  DashboardMapIndexRoute: typeof DashboardMapIndexRoute
}

const DashboardMapLayoutRouteChildren: DashboardMapLayoutRouteChildren = {
  DashboardMapIndexRoute: DashboardMapIndexRoute,
}

const DashboardMapLayoutRouteWithChildren =
  DashboardMapLayoutRoute._addFileChildren(DashboardMapLayoutRouteChildren)

interface DashboardMapsLayoutRouteChildren {
  DashboardMapsIndexRoute: typeof DashboardMapsIndexRoute
  DashboardMapsMapIdIndexRoute: typeof DashboardMapsMapIdIndexRoute
}

const DashboardMapsLayoutRouteChildren: DashboardMapsLayoutRouteChildren = {
  DashboardMapsIndexRoute: DashboardMapsIndexRoute,
  DashboardMapsMapIdIndexRoute: DashboardMapsMapIdIndexRoute,
}

const DashboardMapsLayoutRouteWithChildren =
  DashboardMapsLayoutRoute._addFileChildren(DashboardMapsLayoutRouteChildren)

interface DashboardLayoutRouteChildren {
  DashboardMapLayoutRoute: typeof DashboardMapLayoutRouteWithChildren
  DashboardMapsLayoutRoute: typeof DashboardMapsLayoutRouteWithChildren
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardSyncIndexRoute: typeof DashboardSyncIndexRoute
  DashboardAdminEventsIndexRoute: typeof DashboardAdminEventsIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardMapLayoutRoute: DashboardMapLayoutRouteWithChildren,
  DashboardMapsLayoutRoute: DashboardMapsLayoutRouteWithChildren,
  DashboardAdminRouteRoute: DashboardAdminRouteRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardSyncIndexRoute: DashboardSyncIndexRoute,
  DashboardAdminEventsIndexRoute: DashboardAdminEventsIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
