import { BrandColors } from "../../brand";

import type { MD3Theme } from "./types";

export const AppColors: MD3Theme = {
  light: {
    primary: BrandColors.forestGreen,
    onPrimary: "#FFFFFF",
    primaryContainer: BrandColors.lightGreen,
    onPrimaryContainer: BrandColors.darkForestGreen,
    secondary: BrandColors.tropicalForestGreen,
    onSecondary: "#FFFFFF",
    secondaryContainer: "#B8E6D5",
    onSecondaryContainer: BrandColors.deepForestGreen,
    tertiary: "#3B7A57",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#C5E8D0",
    onTertiaryContainer: "#0D2818",
    error: "#BA1A1A",
    onError: "#FFFFFF",
    errorContainer: "#FFDAD6",
    onErrorContainer: "#410002",
    background: "#F4FBF4",
    onBackground: BrandColors.darkForestGreen,
    surface: "#F4FBF4",
    onSurface: BrandColors.darkForestGreen,
    surfaceVariant: "#D4E8D4",
    onSurfaceVariant: "#2D4A32",
    outline: "#5A7A5E",
    outlineVariant: "#B8D4BC",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: BrandColors.deepForestGreen,
    inverseOnSurface: BrandColors.onDark,
    inversePrimary: BrandColors.limeGreen,
    elevation: {
      level0: "transparent",
      level1: "#E8F5E8",
      level2: "#E0F0E0",
      level3: "#D8EBD8",
      level4: "#D4E8D4",
      level5: "#CFE5CF",
    },
    surfaceDisabled: "rgba(1, 50, 32, 0.12)",
    onSurfaceDisabled: "rgba(1, 50, 32, 0.38)",
    backdrop: "rgba(1, 50, 32, 0.4)",
    surfaceContainer: "#E8F2E8",
    surfaceContainerLow: "#F0F8F0",
    surfaceContainerLowest: "#FFFFFF",
    surfaceContainerHigh: "#DCEADC",
    surfaceContainerHighest: "#D0E4D0",
    surfaceBright: "#FAFDFA",
    surfaceDim: "#D0E0D0",
    surfaceTint: BrandColors.forestGreen,
  },
  dark: {
    primary: BrandColors.limeGreen,
    onPrimary: BrandColors.darkForestGreen,
    primaryContainer: BrandColors.tropicalForestGreen,
    onPrimaryContainer: BrandColors.lightGreen,
    secondary: BrandColors.onDarkMuted,
    onSecondary: BrandColors.deepForestGreen,
    secondaryContainer: "#2A4A38",
    onSecondaryContainer: BrandColors.onDark,
    tertiary: "#6B9B7A",
    onTertiary: BrandColors.deepForestGreen,
    tertiaryContainer: "#3D5C48",
    onTertiaryContainer: "#C5E8D0",
    error: "#FFB4AB",
    onError: "#690005",
    errorContainer: "#93000A",
    onErrorContainer: "#FFB4AB",
    background: BrandColors.darkForestGreen,
    onBackground: BrandColors.onDark,
    surface: BrandColors.darkForestGreen,
    onSurface: BrandColors.onDark,
    surfaceVariant: "#2A4A32",
    onSurfaceVariant: BrandColors.onDarkMuted,
    outline: "#5A8A62",
    outlineVariant: "#2A4A32",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: BrandColors.onDark,
    inverseOnSurface: BrandColors.deepForestGreen,
    inversePrimary: BrandColors.forestGreen,
    elevation: {
      level0: "transparent",
      level1: "#0A2818",
      level2: "#0F3020",
      level3: "#143828",
      level4: "#163A2A",
      level5: "#1A402E",
    },
    surfaceDisabled: "rgba(200, 230, 201, 0.12)",
    onSurfaceDisabled: "rgba(200, 230, 201, 0.38)",
    backdrop: "rgba(1, 50, 32, 0.6)",
    surfaceContainer: BrandColors.deepForestGreen,
    surfaceContainerLow: "#0A2018",
    surfaceContainerLowest: "#051410",
    surfaceContainerHigh: "#1E3828",
    surfaceContainerHighest: "#284432",
    surfaceBright: "#2E5038",
    surfaceDim: "#081810",
    surfaceTint: BrandColors.limeGreen,
  },
};
